---
title: "Forschungsbericht Soziale Netzwerke"
author: "Gruppe 3 | Projektleitung Luisa Funk, lf067@hdm-stuttgart.de"
date: "Wintersemester 2021/22"
---

# Abstract und Keywords

Im Rahmen dieses Forschungsberichts analysieren wir in einem ungerichteten Netzwerk die Beziehungen von insgesamt 55 Zeug*innen, die im Gerichtsprozess von Amber Heard und Johnny Depp (April 2022) ausgesagt haben. Die Beziehungsdimensionen umfassen sechs Attribute: Beziehung, Zeitpunkt des erstmaligen Kennenlernens, belastende, entlastende oder neutrale Aussage und Ereignis. Die Analyse zeigt, dass Johnny Depp besser vernetzt ist. Johnny Depp profitierte vor allem von persönlichen und privaten Beziehungen, die ihn vor Gericht entlastet haben. 
Keywords: Netzwerkanalyse, Beziehungen, Zeugen, Johnny Depp, Amber Heard, Gerichtsprozess

# Einleitung 

## Hintergrund des Prozesses

Depp und Heard lernten sich im Jahr 2009 bei den Dreharbeiten des Films „The Rum Diary“ kennen, in dem beide mitspielten (ZEIT ONLINE, 2022). Die Beziehung zwischen Heard und Depp begann im Jahr 2012, bereits nach drei Jahren folgte die Hochzeit, knapp ein Jahr später dann die Scheidung (ZEIT ONLINE, 2022).
Heard behauptete 2018 in einem Artikel, Opfer von häuslicher Gewalt geworden zu sein (Der Spiegel, 2022). Laut Depp seien die Aussagen falsch, er verklagte sie wegen Verleumdung auf 50 Millionen Dollar. Heard reagierte mit einer Gegenklage auf 100 Millionen Dollar. Der Verleumdungsprozess zwischen Depp und Heard dauerte vom 1. April bis zum 1. Juni 2022 an und fand in Fairfax Counry, Virginia statt (Stern, 2022). 
Am Ende des Prozesses im Juni 2022 entschied das Gericht in Fairfax County, dass Heard ihren Ex-Mann Depp verleumdet hat. Heard muss Depp einen Schadensersatz in Höhe von 15 Millionen Dollar bezahlen. In Heards Gegenklage bekam sie in drei Anklagepunkten Recht. Depp muss ihr deshalb zwei Millionen Dollar Schadensersatz bezahlen (tagesschau.de, 2022).
Herleitung der Forschungsfrage

Der Gerichtsprozess von Amber Heard und Johnny Depp war medial präsent wie kein anderer Prozess in Hollywood. Auch auf Social Media, besonders TikTok und Twitter wurde die Gerichtsverhandlung hitzig diskutiert und es waren zwei deutliche Positionierungen zu erkennen: Team Johnny Depp und Team Amber Heard. 

Beim Gedanken an das Thema wollten wir die beiden Beteiligten nicht in Opfer und Täter*in kategorisieren, sondern differenziert an das Thema herangehen. Dabei wollten wir zudem herausfinden, ob gewisse Beziehungen oder Verflechtungen in Hollywood einem*r der beiden Angeklagte*n geholfen haben könnten. 
Auf Grundlage dieser Teilaspekte entstand folgende Forschungsfrage:

Wie wirkt sich die Beziehung der Zeug*innen untereinander und zu den Angeklagten auf die Aussagen vor Gericht aus?

Vorarbeiten und vergleichbare Studien

Forschungsstand SNA in der Kriminalgeschichte

Die Soziale Netzwerkanalyse (SNA) bietet sich besonders im Bereich der Kriminologie an, weil sie sich nicht auf die klassischen Attribute von Gruppen oder Einzelpersonen fokussiert, sondern auf die Verbindungen zwischen unabhängigen Individuen (Gallupe, 2016). Damit bereichert die SNA die klassische Kriminalforschung.
Die SNA findet sich in der Kriminologie in einem breiten Anwendungsfeld wieder. Sie wird dort beispielsweise angewendet, um die Strukturen von kriminellen Vereinigungen und Schwarzmärkten zu analysieren (Gallupe, 2016). 
Der Einsatz der Netzwerkanalyse in der Kriminologie bietet verschiedene Vorteile. Zum einen das Verhalten von Menschen aus individuellen Strukturen zu erklären (Rau & Höffler, 2020). Außerdem können mithilfe der SNA die einhergehenden Bindungen und Verpflichtungen von bestimmten Akteur*innen zu ihren Kontakten verstanden werden (ebd.). Aber auch, wenn man an die Prävention von Kriminalität denkt, kann sich die SNA als hilfreich erweisen (ebd.).

Forschungsstand True Crime

True Crime gibt es mittlerweile in jeglichen Formaten, beispielsweise in Form von Büchern, Dokumentationen, Serien aber auch Podcast. Mit der Faszination hinter True Crime beschäftigt sich die Psychologie seit langem. Einer der Erkenntnisse war, dass sich die meisten Rezipient*innen für True Crime faszinieren, weil ein gewisser Reiz am Leben “der Anderen” besteht (Dmitrieva, 2017).
Im Fall von Johnny Depp und Amber Heard war dies gut zu erkennen. Viele Menschen haben den Gerichtsprozess mitverfolgt, weil sie sich selbst in der Rolle des “Problemlösers” und “Falllösers” wiederfinden (Ewert, 2019). In den sozialen Medien führte dies unter anderem dazu, dass User*innen eigene Recherchen starteten, um den Fall zu lösen und einen Schuldigen zu finden. Daraus entstanden sind beispielsweise die Hashtags “#IStandwithAmber” oder ‘#JusticeforJohnny”. 

Arbeitshypothesen

Folgende Hypothesen haben wir im Vorhinein aufgestellt und wollten diese mit unserer Netzwerkanalyse beantworten:

(1) Hat Johnny Depp den Gerichtsprozess “gewonnen”, weil er in Hollywood besser vernetzt ist? 

(2) Kann man sagen, dass mehr Männer Johnny Depp entlastet haben und mehr Frauen Amber Heard? 

(3) Wirkt sich die Beziehung der Zeugen untereinander auf ihre Aussagen aus?

Datenerhebung: Zugang, Bereinigung und Codebuch 

Datenzugang

Wir haben unsere Daten über aufgezeichnete Videos des Gerichtsprozesses, die auf dem Youtube-Kanal „Law & Crime Network“ seit April 2022 veröffentlicht wurden, erhoben. Außerdem hatten wir durch das große mediale Interesse Zugang zu Informationen in der Klatschpresse. Da diese Informationen jedoch fraglich wahrheitsgetreu waren, haben wir diese Informationen abgeglichen mit weiteren öffentlich zugänglichen Gerichtsunterlagen. 

Aus dieser intensiven Recherche-Phase haben wir zu allen Zeug*innen eine Art kleinen Steckbrief mit allen relevanten Attributen und Kennzahlen erstellt.  

Bereinigung des Datensatzes

Die Daten aus der Datenerhebung wurden anschließend zusammengetragen und codiert. Im Laufe dieses Prozesses musste die Codierung allerdings bei einigen Attributen aufgrund neuer Erkenntnisse abgeändert werden.

Codebuch

Das [Codebuch] (https://github.com/Laura311000/NovemberJohnnyAmber/blob/main/Codebuch.rmd) umfasst die erhobenen Variablen, Relationen und Gewichte des Netzwerks und ist auf Github hinterlegt.


Erstellung des Datensatzes 

Alle in der Nodelist aufgeführten Personen sind Zeug*innen, welche vor Gericht eine Aussage gemacht haben. Als ID werden die Initialen verwendet. Auch die Protagonist*innen des Gerichtsverfahrens sowie häufig im Prozess erwähnte Ereignisse sind in der Nodelist aufgeführt.
Die Zeug*innen und die Protagonist*innen werden in folgenden Nodeattributen kategorisiert:
Name, sex, age und profession.

In der Edgelist wird die Beziehung der Zeug*innen zu Amber Heard und zu Johnny Depp kategorisiert. Das Edgeattribut Relation klassifiziert die Beziehungen der Zeug*innen zu den Protagonist*innen in folgenden Kategorien.  
Sollten mehrere Kategorien auf die Zeug*innen zutreffen, werden sie mehrfach gelistet.

1 = work/contract  
Die Protagonist*innen standen zu der Zeug*in einem Arbeitsverhältnis oder haben sie am Arbeitsplatz kennengelernt. Beispielsweise Keenan Wyatt ( ID= KW) lernte Johnny Depp 1997 am Set des Films „The Brave“ kennen. Kenan Wyatt arbeitet dort als Toningenieur und Depp fungierte als Director, Drehbuchautor und Hauptdarsteller.

2 = friendship
Unter die Kategorie friendship fallen alle Zeug*innen, die in einem freundschaftlichen Verhältnis zu den Protagonist*innen stehen.

3 = love
Unter die Kategorie love fallen alle Zeug*innen, die in einer Liebesbeziehung zu den Protagonist*innen stehen oder in der Vergangenheit in einer Liebesbeziehung zu ihnen standen.

4 = employed by
Unter die Kategorie employed by fallen alle Zeug*innen, in einem Angestelltenverhältnis zu den Protagonist*innen standen. Beispielsweise Kate James (ID=KJ) war zwischen 2012 -2015 als persönliche Assistentin von Amber Heard angestellt.

5 = medizinische Dienstleister
Unter die Kategorie medizinische Dienstleister fallen alle Zeug*innen, welche die Protagonist*innen medizinisch (physisch oder psychisch) versorgt haben.

6= family 
Unter die Kategorie family fallen alle Zeug*innen, die in einem familiären Verhältnis zu den Protagonist*innen stehen.

7= extern
Unter die Kategorie extern fallen alle Zeug*innen, die in keinem persönlichen Verhältnis zu den Protagonist*innen stehen und trotzdem vor Gericht ausgesagt haben. Darunter fallen vor allem Sachverständige oder Gutachter*innen.

8= Wohnhauskomplex 
Unter die Kategorie Wohnhauskomplex fallen alle Zeug*innen, welche in einem der Wohnhäuser der Protagonist*innen gelebt haben.

Das Edgeattribut time beschreibt den Zeitpunkt, an dem sich Zeug*innen und Protagonist*innen kennengelernt haben, falls dieser festgestellt werden konnte.
WeightJD und WeightAH kategorisieren die Aussagen der Zeug*innen zu den Protagonist*innen nach a=belastet und b= entlastet und c=neutral.
Das Attribut Event zeigt an, ob Zeug*innen zu eines der häufigsten genannten Events ausgesagt hat ( Finger abschneiden, Kot im Bett, Polizeieinsatz und Wohnkomplex)
Gesamtnetzwerk

# Erstellung eines Gesamtnetzwerkes mit allen Zeug*innen und den am häufigsten gennannten Events.
#Nodeattribut sex wird eingefärbt für eine bessere Übersicht.
In unserem Gesamtnetzwerk werden alle Zeug*innen, Amber Heard und Johnny Depp sowie die 4 am häufugsten gennanten Ereignisse gezeigt. Die beiden Events mit den meisten Kanten werden im Abschnitt Teilnetzwerke besprochen.
Analyse der Teilnetzwerke
Bei der Auswahl der Teilnetzwerke haben wir uns an der Forschungsfrage orientiert: Wie wirkt sich die Beziehung der Zeug*innen untereinander und zu den Angeklagten auf die Aussagen vor Gericht aus?
Das erste Teilnetzwerk zeigt alle Zeug*innen, die mit ihrer Aussage eine der beiden Protagonist*innen entlastet haben.
# erstellt Teilnetzwerk aller Zeug*innen mit dem Edgeattribut b= entlastet.
Auf den ersten Blick erkennt man durch dieses Teilnetzwerk, dass mehr als doppelt so viele Zeug*innen Johnny Depp entlasten als Amber Heard.
Um zu vergleichen, was diese Zeug*innen gemeinsam haben könnten und um es einen Unterschied zwischen den beiden Gruppen gibt haben wir uns die Beziehungen zueinander angeschaut und eingefärbt.
# Erstellung der Subgraphs und einfärben des Edgeattribut relation in verschiedene Farben.
Neun der 13 Zeug*innen standen in einer Beziehung zu Amber Heard. Fünf davon in einer externen Beziehung, das bedeutet, dass sie von Amber Heards Team als Gutachter*innen zu verschiedenen Themen geladen wurden. Beispielsweise Julian Ackert, der als Computerforensiker Bilder von Ambers Verletzungen auf Wahrhaftigkeit untersuchen sollte.
Amy Banks, eine der entlastenden Zeug*innen, fällt mit zwei weiteren unter die Kategorie fünf (medizinischen Beziehung). Sie war Amber Heards Psychotherapeutin. Tillet Wright, ein Freund von Amber, sagte entlastend für sie aus und fällt in Kategorie zwei (friendship). Das vier restliche Zeug*innen standen in keiner Beziehung zu Heard, jedoch zu Johnny Depp. Ihre entlastende Aussage für Heard ist durch eine aktiv belastende Aussage für Depp entstanden.
Im Vergleich fällt das entlastende Netzwerk von Johnny Depp um einiges bunter aus. Wie auch bei Amber stehen 4 Zeug*innen nicht in einer direkten Beziehung zu Johnny Depp. Da insgesamt 34 Zeug*innen Depp entlastet haben, standen 30 in einer Beziehung zu ihm. Besonders häufig wurde er von Zeug*innen entlastet, die in einem Angestelltenverhältnis zu Depp standen oder stehen(10 edges für employed by). Auch drei seiner Exfreundinnen (love) und drei seiner Freund*innen (friendship) haben entlastend für Depp ausgesagt.
Mit Blick auf Arbeitshypothese (1) lässt sich daraus schließen, dass Johnny Depp eine bessere Vernetzung zu seinen Zeug*innen pflegte. Während Amber Heard hauptsächlich auf externe Verbindungen angewiesen war, profitierte Depp vor allem durch seine persönlichen Kontakte. Das bedeutet für unsere Forschungsfrage, dass die Art der Beziehung von den Zeug*innen zu den Angeklagten eine Rolle vor Gericht zu spielen scheint. Es ist jedoch schwierig zu beurteilen, ob das Gericht die Aussage einer externen Person weniger gewichtet als die Aussage einer des*der Protagonist*in bekannten Person. Von außen betrachtet scheint vor allem die Anzahl der Zeug*innen ein größerer Faktor zu sein. Dort punktete Depp mit einer eindeutigen Mehrheit. 
Teilnetzwerk Entlasten
Für Arbeitshypothese (2) Kann man sagen, dass mehr Männer Johnny Depp entlastet haben und mehr Frauen Amber Heard?  haben wir folgendes Netzwerk erstellt.

Zeug*innen werden nach dem Nodeattribut sex in männlich und weiblich eingefärbt und ein Teilnetzwerk mit allen entlastenden Zeugen (Edgeattribut b) für Amber und Johnny erstellt.

Schnell ist zu erkennen, dass für Amber Heard vor allem Frauen entlasten ausgesagt haben (9 von 13). Bei Johnny Depp waren die Männer in der Überzahl, die entlasten für ihn aussagten. Damit lässt sich die Hypothese zumindest teilweise bestätigen. Trotzdem lässt sich die Hypothese nicht generalisieren, da die Anzahl der entlastenden Aussagen der beiden Protagonist*innen so stark voneinander abweichen und nicht gut zu vergleichen sind.

Teilnetzwerke zu den Events

Während der Recherche des Gerichtsprozesses sind uns zwei Fälle aufgefallen, zu denen die meisten Zeug*innen befragt wurden. Besonders interessant ist die Tatsache, dass in beiden Events die Mehrheit der Zeug*innen miteinander in Verbindung standen. Wir haben zu beiden Events Teilnetzwerke erstellt, um die Verbindung der Zeug*innen untereinander sowie zu Johnny Depp und Amber Heard besser analysieren und nachvollziehen zu können. Bei beiden Events sind wir ähnlich vorgegangen.


Event Finger abschneiden 

Bei dem ersten Teilnetzwerk (FA), handelt es sich um einen Vorfall, welcher im März 2015 in Australien stattgefunden haben soll. Depp behauptet, dass Heard ihm bei einem Streit mit einer Wodkaflasche bewarf und ihm dadurch die Fingerkuppe des Mittelfingers der rechten Hand abtrennte. Heard bestritt dies und warf stattdessen Depp vor, sie mit einer Schnapsflasche sexuell misshandelt zu haben. 

#Die Beziehungen, die mit einem der Events in Zusammenhang stehen, in der edgeliste markieren. 

#Mit dem Befehl “subgraph.edges” die Knoten mit den dazugehörigen Kanten zu dem jeweiligen Event auswählen.

#Um die einzelnen Beziehungen, die die Knoten untereinander haben, besser nachvollziehen zu können, haben wir das Edge-Attribute relation in unterschiedlichen Farben eingefärbt. 

Dabei ist uns aufgefallen, dass es sich bei der Mehrheit der Zeug*innen um Dienstleister*innen oder medizinisches Personal handelt. Dies ist an den blauen Kanten zu sehen, sie stehen für relation = medizinische Dienstleister und relation = employed by. Wir konnten auch erkennen, dass mehr blaue Kanten zu Depp führen, als zu Heard. Vier der fünf Zeuge*innen wurden demnach von Depp für eine Dienstleistung bezahlt. 

Darüber hinaus ist das medizinische Team, bestehend aus Kipper, Lloyd und Bean, miteinander vernetzt. Sie sind Kolleg*innen und arbeiten gemeinsam in der Privatpraxis. Dies ist an den grünen Kanten, welche relation = work markieren, feststellbar. Sie waren von beiden Angeklagten angestellt, aber es gibt mehr Verbindungen zu Depp.

Auffällig ist Dr. Richard Moore (ID= DRM). Er hat zu keinem anderen Knoten, außer dem Eventknoten, eine Verbindung. Seine Kante geht nur zu dem Event “Fingerabschneiden” und ist türkis für die relation = extern eingefärbt. Moore wurde extern als Gutachter geladen und sagt als Einziger entlastend für Heard aus.

In diesem Teilnetzwerk sagt die Mehrheit der Zeug*innen belastend für Heard und entlastend Depp aus. Dies lässt sich durch die türkis eingefärbten Knoten erkennen. 

Ben King (ID =BK) der Housemanager wurde von Depp angestellt, aber entlastet weder Depp noch Heard. Einzig Richard Moore, der externe Gutachter, hat Heard entlastet. Daraus lässt sich schließen, dass das Personal enger mit Depp war und auch primär von ihm angestellt und bezahlt wurde. Im Besonderen hat das medizinische Team rund um Dr. Kipper ein enges Verhältnis zu Depp, sodass alle ihn entlasten.


Event Wohnkomplex

Johnny Depp besaß während der Beziehung zu Heard einen Penthousewohnkomplex im Eastern Columbia Building in Los Angeles. In diesen Wohnungen haben während der Ehe von Depp und Heard mehrere Freund*innen des Paares gewohnt. Sie hatten unterschiedliche Beziehungen zu Depp und Heard und haben ebenfalls vor Gericht als Zeug*innen ausgesagt. Die Zeug*innen waren aber nicht nur Nachbar*innen, sondern beispielsweise auch enge Familienangehörige, wie die Schwester von Heard, Whitney Henriquez (ID=WHE). Andere, wie der Künstler Isaac Baruch (ID = IB), waren jahrelange Freunde von einem der Angeklagten. Depp ließ Baruch für mehrere Jahre kostenlos in einer der luxuriösen Wohnungen leben und unterstützte ihn immer wieder mit Geld. Auch Heards Freundin Raquelle Peninngton (ID = RP) und deren Ehemann Josh Drew (ID= JDR) sind über Heard in eine von Depps Penthousewohnungen eingezogen. Besagt Nachbar*innen wurden als Zeug*innen im Prozess verhört. Sie sollten sich zu der Beziehung zwischen Heard und Depp sowie den Anschuldigungen, dass Depp Heard körperlich misshandelt hätte, aussagen.


Die roten Kanten im Netzwerk markieren das “Mietverhältnis” der vier Zeug*innen durch relation = Wohnkomplex. Alle vier haben in Depps Wohnungen gelebt. Drei der vier Zeug*innen hatten ein freundschaftliches Verhältnis zu Heard. Dies ist an den blauen Kanten relaton = friendship erkennbar. Die andere Zeugin war ihre Schwester, diese Kante ist durch relation = family grün eingefärbt. 

Im Prozess wurde Heard nur von ihrer Schwester entlastet. Sie gab an, gesehen zu haben, wie Depp Heard körperlich misshandelte. Der Rest der Wohnkomlexbewohner*innen entlastete Depp im Verhör und gab an, keine körperliche Gewalt beobachtet zu haben. 

Obwohl Heard mehr Freund*innen in der Nachbarschaft hatte, haben sich diese im Verhör alle von ihr abgewandt. Die Beschuldigungen, die Heard gegenüber Depp geäußert hatte, konnten nur von ihrer Schwester bestätigt werden. 

Daraus lassen sich zwei Vermutungen schlussfolgern. Entweder sind ihre Anschuldigungen frei erfunden und ihre Schwester in den Komplott eingeweiht. 
Oder die Verbindung zwischen Depp und den Bewohner*innen ist durch die”Vermietung” der Wohnungen so eng geworden, dass sie sich entschieden haben für ihn auszusagen.


Diskussion: Fazit, Limitationen und Ausblick 

Fazit

Unsere Arbeitshypothesen (siehe oben) haben sich größtenteils bestätigt. Wir sind bei unserer Analyse auf keine besonders überraschenden oder unerwarteten Erkenntnisse gestoßen. 

Limitationen 

Da unter den Zeug*innen des Prozesses auch einige Privatpersonen waren, erschwerte uns dies die Suche nach persönlichen Daten oder persönlichen Verbindungen zu anderen Zeug*innen oder den Hauptakteur*innen des Prozesses. Aus diesem Grund konnten wir nur Verflechtungen herausfinden, die öffentlich zugänglich waren. 

Zur Feststellung, ob eine Aussage als belastend oder entlastend einzustufen ist, gibt es keine einheitlichen Vorgaben. Jede Aussage musste von uns selbst analysiert und nach subjektivem Empfinden eingeordnet werden.

Außerdem erkannten wir schlussendlich, dass die Mehrheit an Knoten untereinander keine Verbindung hatten. Somit erschwerte uns dies, prägnante und aussagekräftige Ergebnisse zu erläutern. 




Anlage

Literatur

tagesschau.de. (2022). Johnny Depp gegen Amber Heard: Depp kriegt Recht - teilweise. tagesschau.de. Abgerufen 21. Dezember 2022, von https://www.tagesschau.de/ausland/amerika/urteil-depp-heard-101.html

Der Spiegel (2022, Mai 4). Johnny Depp: Amber Heard scheitert mit Antrag auf Abweisung von Depps Klage. .https://www.spiegel.de/panorama/leute/amber-heard-scheitert-mit-antrag-auf-abweisung-von-johnny-depps-klage-a-45a03588-2966-4fab-b7d1-d5a9f700625c

STERN.de. (2022). Amber Heard und Johnny Depp: Von der Filmliebe zur Schlammschlacht |  Abgerufen 21. Dezember 2022, von https://www.stern.de/lifestyle/leute/amber-heard-und-johnny-depp--von-der-filmliebe-zur-schlammschlacht-31802960.html

Die Zeit.(2022, Juni 2). Urteil in Verleumdungsprozess: Heard gegen Depp: Jury entscheidet größtenteils für Depp.https://www.zeit.de/news/2022-06/01/urteil-im-rosenkrieg-depp-gegen-heard-gegen-21-00-uhr
Ewert, L. (2019, Januar 31). Trennungen von Promis: Woher kommt die Faszination am Liebesleid? DIE WELT. https://www.welt.de/iconist/partnerschaft/article187823420/Trennungen-von-Promis-Wo
Gallupe, O. (2016). Network Analysis. In The Handbook of Measurement Issues in Criminology and Criminal Justice (S. 555–575). John Wiley & Sons, Ltd. https://doi.org/10.1002/9781118868799.ch25
Rau, M., & Höffler, K. (2020). Soziale Netzwerkanalyse in der deutschsprachigen Kriminologie: Vorhandenes, Herausforderungen und Potentiale. Kriminologie - Das Online-Journal | Criminology - The Online Journal, 1, Art. 1. https://doi.org/10.18716/ojs/krimoj/2020.1.3
Bichler, G. (2019). Understanding Criminal Networks: A Research Guide. Univ of California Press.
Buhl, G. (2022, Oktober 14)«The Jeffrey Dahmer Story»—Warum unser Gehirn süchtig nach True Crime ist. Schweizer Radio und Fernsehen (SRF). https://www.srf.ch/wissen/mensch/the-jeffrey-dahmer-story-warum-unser-gehirn-suechtig-nach-true-crime-ist
 Dmitrieva, K. (2017). Why Are We Fascinated with Violence?  An Investigation of Mass Media’s Role in Depicting Violence as Entertainment. Senior Honors Projects. https://digitalcommons.uri.edu/srhonorsprog/574

Codebuch

Das [Codebuch] https://raw.githubusercontent.com/Laura311000/NovemberJohnnyAmber/main/Codebuch.rmd

Das Netzwerk hat nach dem  [Codebuch] folgende Attribute:


Datenmaterial und Skript

[Datensatz]
https://github.com/Laura311000/NovemberJohnnyAmber 

Teambewertung, Arbeitsaufwand pro Teammitglied und Lessons learned 

Teammitglieder

Laura Wallenfels, Karolina Bischoff, Samira Igwe, Tiana Kleyer, Theresa Moretti

Arbeitsaufwand pro Teammitglied

Laura Wallenfels: Recherche Coding, Endbericht, Visualisierung: 25h
Samira Igwe: Recherche, Literaturrecherche, Präsentation: 25h
Karolina Bischoff: Recherche, Coding, Visualisierung: 25h
Tiana Kleyer: Recherche, Endbericht, Präsentation: 25h
Theresa Moretti: Recherche, Coding, Endbericht: 25h
Lessons learned
Unsere Lessons Learned sind, Termine früh festzulegen und sich einen Zeitplan zu erstellen. Wir hatten aufgrund von vielen weiteren Projekten dieses Semesters Schwierigkeiten, Meeting-Termine zu finden, an denen alle Gruppenmitglieder Zeit finden konnten. Eine Gruppe von fünf Personen war in der Arbeitsaufteilung hilfreich, um so schneller, präziser und gewissenhafter zu arbeiten, bei der Zeitfindung für Meetings jedoch äußerst schwierig.   
